blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/dfront/gdrive_permissions1#documentation-map
    about: Review the documentation before filing an issue.
